### Enregistrer un étudiant
POST http://127.0.0.1:8000/authapp/signup/
Content-Type: application/json

{
    "nom": "tes1",
    "email": "tes@test1.com",
    "role": "etudiant",
    "matricule": "21T2726",
    "password": "test",
    "niveau": "1"
}


### Enregistrer un délégué
POST http://127.0.0.1:8000/authapp/signup/
Content-Type: application/json

{
    "nom": "Ma Laetita",
    "email": "mf.ngaleu@gmail.com",
    "role": "delegue",
    "matricule": "21T2413",
    "password": "654759921",
    "niveau": "1"
}


### Enregistrer un Administrateur
POST http://127.0.0.1:8000/authapp/signup/
Content-Type: application/json

{
    "nom": "Aminou ALidou",
    "email": "alidou.aminou@facsciences-uy1.cm",
    "role": "administrateur",
    "matricule": "0000000",
    "password": "admin"
}



###Login et recuperation des informations d'un administrateur dans la base
POST http://127.0.0.1:8000/authapp/login/
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "admin"
}

###
POST http://127.0.0.1:8000/authapp/login/
Content-Type: application/json

{
    "email": "maffo.ngaleu@gmail.com",
    "password": "654759921"
}




########################################################################
###Login et recuperation des informations d'un utilisateur dans la base
POST http://127.0.0.1:8000/authapp/login/
Content-Type: application/json

{
    "email": "betty.ebai@facsciences-uy1.cm",
    "password": "123lucky"
}



###### Rafraîchir le token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMjM1MDExNCwiaWF0IjoxNzMyMjYzNzE0LCJqdGkiOiJlNjY1NGZmYTk2MjE0Y2NiODk5MGVkZmQ1NjFiNjhjYiIsInVzZXJfaWQiOjF9.kYb7yfwOkRIEU_etdbummJS-ljYpiipfUdjlEJ-5isk"
}





###Obtenir la liste des delegues
GET http://127.0.0.1:8000/authapp/pending-delegates/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjE5MjE2LCJpYXQiOjE3MzQ2MTU2MTYsImp0aSI6IjZjNzcwNDMyZGY1OTQyMTU4ZDRlOThmY2I3ODRjNTMzIiwidXNlcl9pZCI6MX0.s2wHJ8GB7-t5HhsOFgExhWSGhxKpkVwuqUxzetloA7w

{}




### Approuver un délégué (avec authentification)
POST http://127.0.0.1:8000/authapp/approve-delegate/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjE3MjY3LCJpYXQiOjE3MzQ2MTM2NjcsImp0aSI6ImQ1YWMxNWQ5MTJkOTQyMDZiN2FhYmMzNDNiOWY4NTU3IiwidXNlcl9pZCI6MX0.Iz59ciKSqtWDItM3y6MxhSTT1wrS1iF5SLhgUmZ4FR0

{
    "user_id": 3
}