# Generated by Django 5.1.3 on 2024-11-28 02:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0003_remove_reservation_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='equipments',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='validation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
