# Generated by Django 5.1.3 on 2024-11-28 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0004_hall_equipments_reservation_validation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='level',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
