###recuperation informations on a user's token.

POST http://127.0.0.1:8000/authapp/login/
Content-Type: application/json 

{
    "email": "betty.ebai@facsciences-uy1.cm",
    "password": "123lucky"
}

### Check permission to make reservation. 
POST http://127.0.0.1:8000/api/permission/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjI4MTcxLCJpYXQiOjE3MzQ2MjQ1NzEsImp0aSI6IjU3ZTE4ZmYzMTFiMDRhODA5Njc5MjVhNmM2YmVmMGJmIiwidXNlcl9pZCI6NH0.0gw15bcKq5pAFnbNAX17tNBP7R-LlORTl5QXcf5obWI
###

### Research available halls on a specific date
GET http://127.0.0.1:8000/api/research/2024-12-30/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc
###

### Make a reservation
POST http://127.0.0.1:8000/api/make-reservation/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc
Content-Type: application/json

{
    "hall_id": 1,
    "course_name": "bb",
    "professor_email": "nana.heil@facsciences-uy1.cm",
    "start_time": "7:30:00",
    "end_time": "9:00:00",
    "date": "2024-12-24"
}

###

### Validate reservation
GET http://127.0.0.1:8000/api/validate-reservation/0055caf0-9f34-4c47-a2a1-bcdf83c2d7dd


### Profile
GET http://127.0.0.1:8000/api/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc
###

### Get information about a reservation. Any authenticated person can do this if he has the reservation id
GET http://127.0.0.1:8000/api/info-reservation/64/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc


### Potential Reservations to Cancel (Delegate)
GET http://127.0.0.1:8000/api/potential-reservations-to-cancel/delegate/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc

### Potential Reservations to Cancel (Head of Department)
GET http://127.0.0.1:8000/api/potential-reservations-to-cancel/2024-12-01/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0MTQwOTUwLCJpYXQiOjE3MzQxMzczNTAsImp0aSI6IjZmMGU5ZWQ4OTgwNDQ3MWM5YzA0ZWIyYzJmYWZmOTk1IiwidXNlcl9pZCI6MX0.KS-t5Tto1oaoe9wCDAfiKPyNr3hZfm_YN_qqudiO9YQ

###

### Cancel Reservation
DELETE http://127.0.0.1:8000/api/cancel-reservation/57/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc

###

### Cancel All Reservations
DELETE http://127.0.0.1:8000/api/cancel-all-reservations/2024-12-01/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0MTQwOTUwLCJpYXQiOjE3MzQxMzczNTAsImp0aSI6IjZmMGU5ZWQ4OTgwNDQ3MWM5YzA0ZWIyYzJmYWZmOTk1IiwidXNlcl9pZCI6MX0.KS-t5Tto1oaoe9wCDAfiKPyNr3hZfm_YN_qqudiO9YQ

###

### Auto Delete Expired Reservations
DELETE http://127.0.0.1:8000/api/auto-delete-expired-reservations/

### Get reservations by level
GET http://127.0.0.1:8000/api/reservations-by-level/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc

### Get notifications by level
GET http://127.0.0.1:8000/api/notifications-by-level/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NjMwOTgwLCJpYXQiOjE3MzQ2MjczODAsImp0aSI6Ijk5YmNlNGU4MTU1YjQ4ZGVhNGNiMzY1ODUwYmNmYzIzIiwidXNlcl9pZCI6NH0.zaD8RP3sjgK0kDF3AdvXudSGcUMQqIgA76xuHwwW_Fc